spring:
  datasource:
    url: jdbc:mysql://172.17.38.163:3306/flowable_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: flowable
    password: flowable123

flowable:

server:
  port: 28080